title: Angus Fiedler
logo: /assets/img/Angus_Fiedler_Round.png
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal
description: Postbaccalaureate Premed Student at Bryn Mawr College. Looking to leverage my Software Engineering background to improve technology in healthcare.
